### ISSUE TITLE
Memory problem when replaying large streams

### ISSUE THREAD

**Issue by codeliner** [prooph/event-store-doctrine-adapter#35]
When replaying a large stream it is possible to run out of memory. Even if the [DoctrineStreamIterator](https://github.com/prooph/event-store-doctrine-adapter/blob/master/src/DoctrineStreamIterator.php) iterates over the pdo statement so that only one event is stored in a php property at a time, the entire result set is fetched into php process memory (at least when using MySql RDBMS, other systems were not checked). This is caused by buffered query mode which is default for MySql. You can turn of the mode but the drawback is that you can only run one unbuffered query per connection at the same time.

See [chat history](https://gitter.im/prooph/improoph?at=574db8a210f0fed86f49e732) for more details.

**Solution:** 
Rewrite DoctrineStreamIterator to use pagination internally and fetch 1000 events at once.

**Comment by basz** [comment]
fyi

- this does not work for me : http://www.dragonbe.com/2015/07/speeding-up-database-calls-with-pdo-and.html
- unreadable solution with yield : http://blog.gigavoice.com/utilize-db-cursors-in-php/

that last one seems to work : https://gist.github.com/basz/f804eeb73e0f8edfc43ffa9b82d1addd

**Comment by prolic** [comment]
Ping @ocramius @olekhy

**Comment by basz** [comment]
update on 'yield'. on closer inspection that also increased memory just after the `stmt->execute` method. see https://gist.github.com/basz/f804eeb73e0f8edfc43ffa9b82d1addd#file-gistfile2-txt-L34

I believe we are back to the iterator around a paginator solution.

**Comment by Ocramius** [comment]
What is the actual cause for the memory issue here, is it the DBAL or is it just PDO mysql being broken?

**Comment by basz** [comment]
We've tested with PDO so DBAL is not the problem. I now think PDO is not broken and is actually performing as it should...

**Comment by codeliner** [comment]
yep, our assumption was broken, caused by `PDOStatement::fetch`. Description of the method (also in doctrine\dbal docs) let you think that only one row is fetched from db at a time, but this is not the case when using MySql with buffered queries (default).

**Comment by Ocramius** [comment]
Can someone write an integration test exposing the problem? The test would basically be:

```
$r1 = iterate_over_a_gazillion_records();
$memory = measure_memory();
$r2 = iterate_over_a_gazillion_records();
self::assertLessOrEqualThan($memory * 1.5, measure_memory());
```

We can then

**Comment by codeliner** [comment]
@Ocramius @basz did some testing: https://gist.github.com/basz/f804eeb73e0f8edfc43ffa9b82d1addd#file-gistfile2-txt-L34

The "problem" is also documented here: http://php.net/manual/de/mysqlinfo.concepts.buffering.php
> Queries are using the buffered mode by default. This means that query results are immediately transferred from the MySQL Server to PHP and then are kept in the memory of the PHP process. 

So no matter if you use `PDOStatement::fetch` or `PDOStatement::fetchAll` (or doctrine\dbal wrapper methods) as long as you run a buffered query the entire db result is copied into PHP memory.

**Comment by Ocramius** [comment]
Yeah, so paginating it is then. I don't think that MySQL related extensions will get any support for cursors in any near future.
