### ISSUE TITLE
Schema files not in sync

### ISSUE THREAD

**Issue by mikemix** [prooph/event-store-doctrine-adapter#38]
Please update [schema](https://github.com/prooph/event-store-doctrine-adapter/tree/master/scripts) files. Missing `causation_id` and `causation_name` fields.

**Comment by prolic** [comment]
No, this is only a template. The event store itself does not rely on having causation_id and causation_name as fields. This is only added by a [plugin](https://github.com/prolic/event-store-bus-bridge/blob/master/src/TransactionManager.php). You can also have many additional fields, so if you need some more fields, you have to create your own schema.

**Comment by prolic** [comment]
BTW: the next major version of prooph's event-store will allow you to inject schema and index definitions.
