### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by timiTao** [prooph/event-store-doctrine-adapter#42]
Could you provide more detailed documentation, about how to configure this?

**Comment by basz** [comment]
Sure, but to get started;

A. Could you provide information about where you are stuck? Is it with this module or the event-store configuration itself?
B. Our professor-do demo application shows how to configure stuff - in the config directory.

**Comment by timiTao** [comment]
Please, descripbe options that i could use in Adapter:
https://github.com/prooph/event-store-doctrine-adapter/blob/master/src/Container/DoctrineEventStoreAdapterFactory.php#L60 and other in factory than i could send via configuration to adapter
https://github.com/prooph/event-store/blob/master/docs/interop_factories.md#event-store-factory

**Comment by basz** [comment]
Did you notice `'stream_name' => 'user_stream'` on that second link? That `user_stream' should go into the doctrine config `stream_table_map`. And is is how the doctrine adapter knows how to use what table for streams.

> And why nowhere i could find information about proophessor-do. When you mentioned this, i look for that.

We are aware we should create additional documentation. Not sure if it is currently actively worked on, but there are some plans... 

Do you know about https://gitter.im/prooph/improoph ? That's an active chat your welcome to ask anything...

Here a copy of some of my configuration;
```
    'prooph'    => [
        'event_store'    => [
            'plugins'                                              => [
                \Prooph\EventStoreBusBridge\EventPublisher::class,
                \Prooph\EventStoreBusBridge\TransactionManager::class,
                \Prooph\Snapshotter\SnapshotPlugin::class,
            ],
            // repeat for every aggregate 
            \Domain\Identity\Aggregate\User::class        => [
                'repository_class'         => \Infrastructure\Repository\Identity\UserRepository::class,
                'aggregate_type'           => \Domain\Identity\Aggregate\User::class,
                'aggregate_translator'     => \Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator::class,
                'snapshot_store'           => \Prooph\EventStore\Snapshot\SnapshotStore::class,
                'stream_name'              => 'user_stream',
                // you may create multiple streams one for each aggregate. However the doctrine adapter does not support that option
                'one_stream_per_aggregate' => false,
            ],
            // more aggregates
```
doctrine adapter
```
    'prooph'    => [
        'event_store'    => [
            'adapter' => [
                'type'    => Prooph\EventStore\Adapter\Doctrine\DoctrineEventStoreAdapter::class,
                'options' => [
                    // alias to a service that creates a dbal connection or simply 'connection' with options that go into Doctrine\DBAL\DriverManager::getConnection($config['connection'])
                    'connection_alias' => 'doctrine.connection.default',

                    // mysql/pdo will load all events into memory, unless a batch size is specified (php will run out of memory otherwise)
                    'load_batch_size' => 10000,

                    // maps one or more stream names to a table names
                    'stream_table_map' => [
                        'user_stream'    => 'tablename_of_events",
                        // more mappings
                    ],
                ],
            ],
        ],
    
```

**Comment by timiTao** [comment]
That helps a lot. Thanks. Counting of publishing documentation. 👍
