### ISSUE TITLE
TableNotFoundException for existing table

### ISSUE THREAD

**Issue by basz** [prooph/event-store-doctrine-adapter#44]
> Did someone already had an issue with the doctrine adapter + mysql where the event is written to the table but you still get a TableNotFoundException?

> Sascha-Oliver Prolic @prolic 16:41
> If you use a single stream, you have to create that table before you run the application

> Fábio Carneiro @fabiocarneiro 16:41
> I did that, the row is inserted.

> Sascha-Oliver Prolic @prolic 16:41
> Oho

> Fábio Carneiro @fabiocarneiro 16:42
> the event is being stored, but the app still says "TableNotFoundException"
> Oo

> Sascha-Oliver Prolic @prolic 16:42
> Can you provide a reproducible script?
> Than open an issue an we can solve that
> Without a test case it's hard.
> Or harder 
> In proophessor-do f.e. i never saw such an issue

> Fábio Carneiro @fabiocarneiro 16:44
> @prolic Base table or view not found: 1146 Table 'testdatabase.event_stream' doesn't exist
but on the database itself, I not only have the table, but the events are being written properly

> Sascha-Oliver Prolic @prolic 16:44
> And you're sure it exists?

> Fábio Carneiro @fabiocarneiro 16:45
> 100%

> Sascha-Oliver Prolic @prolic 16:45
> Can you provide a test script?

> Bradley Weston @bweston92 16:45
> The 1146 is the error code from MySQL

> Fábio Carneiro @fabiocarneiro 16:45
> yep, but then its translated to an exception by doctrine DBAL "Connection"

> Sascha-Oliver Prolic @prolic 16:45
> Please open an issue at the doctrine adapter repo

> Fábio Carneiro @fabiocarneiro 16:46
> I'll try to investigate it and create a failing testcase

> Sascha-Oliver Prolic @prolic 16:46
> @basz can you take that over?

**Comment by fabiocarneiro** [comment]
The problem had nothing to do with prooph or doctrine. I was using `204 No Content for testing purposes on the write side only. Chrome doesn't replace the content no matter how many times you refresh the page and it receives a 204 response, still showing the previous error.

**Comment by basz** [comment]
good

Tip. In the developer tools of chrome you can right click an entry in the network tab with the option to copy the network request as 'curl' command. I then use those commands simply in the terminal. No caching.. :-)

[postman](getpostman.com) is also a good help
